spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false

    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true


application:
  security:
    jwt:
      secret-key: ${SECRET_KEY}
      expiration: 86400000 #1 day
      refresh-token:
        expiration: 604800000 #7 day

  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
server:
  port: 8050

